apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: seldondeployments.machinelearning.seldon.io
spec:
  group: machinelearning.seldon.io
  names:
    kind: SeldonDeployment
    plural: seldondeployments
    shortNames:
    - sdep
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            predictors:
              items:
                properties:
                  graph:
                    properties:
                      children:
                        type: array                        
                        items:
                          properties:
                            children:
                              type: array
                              items:
                                properties:
                                  children:
                                    type: array
                                    items:
                                      properties:
                                        children:
                                          type: array
                                          items:
                                            properties:
                                              endpoint:
                                                properties:
                                                  service_host:
                                                    type: string
                                                  service_port:
                                                    format: int32
                                                    type: integer
                                                  type:
                                                    type: string
                                                type: object
                                              envSecretRefName:
                                                type: string
                                              implementation:
                                                type: string
                                              methods:
                                                items:
                                                  type: string
                                                type: array
                                              modelUri:
                                                type: string
                                              name:
                                                type: string
                                              parameters:
                                                items:
                                                  properties:
                                                    name:
                                                      type: string
                                                    type:
                                                      type: string
                                                    value:
                                                      type: string
                                                  type: object
                                                type: array
                                              serviceAccountName:
                                                type: string
                                              type:
                                                type: string
                                            type: object
                                        endpoint:
                                          properties:
                                            service_host:
                                              type: string
                                            service_port:
                                              format: int32
                                              type: integer
                                            type:
                                              type: string
                                          type: object
                                        envSecretRefName:
                                          type: string
                                        implementation:
                                          type: string
                                        methods:
                                          items:
                                            type: string
                                          type: array
                                        modelUri:
                                          type: string
                                        name:
                                          type: string
                                        parameters:
                                          items:
                                            properties:
                                              name:
                                                type: string
                                              type:
                                                type: string
                                              value:
                                                type: string
                                            type: object
                                          type: array
                                        serviceAccountName:
                                          type: string
                                        type:
                                          type: string
                                      type: object
                                  endpoint:
                                    properties:
                                      service_host:
                                        type: string
                                      service_port:
                                        format: int32
                                        type: integer
                                      type:
                                        type: string
                                    type: object
                                  envSecretRefName:
                                    type: string
                                  implementation:
                                    type: string
                                  methods:
                                    items:
                                      type: string
                                    type: array
                                  modelUri:
                                    type: string
                                  name:
                                    type: string
                                  parameters:
                                    items:
                                      properties:
                                        name:
                                          type: string
                                        type:
                                          type: string
                                        value:
                                          type: string
                                      type: object
                                    type: array
                                  serviceAccountName:
                                    type: string
                                  type:
                                    type: string
                                type: object
                            endpoint:
                              properties:
                                service_host:
                                  type: string
                                service_port:
                                  format: int32
                                  type: integer
                                type:
                                  type: string
                              type: object
                            envSecretRefName:
                              type: string
                            implementation:
                              type: string
                            methods:
                              items:
                                type: string
                              type: array
                            modelUri:
                              type: string
                            name:
                              type: string
                            parameters:
                              items:
                                properties:
                                  name:
                                    type: string
                                  type:
                                    type: string
                                  value:
                                    type: string
                                type: object
                              type: array
                            serviceAccountName:
                              type: string
                            type:
                              type: string
                          type: object
                      endpoint:
                        properties:
                          service_host:
                            type: string
                          service_port:
                            format: int32
                            type: integer
                          type:
                            type: string
                        type: object
                      envSecretRefName:
                        type: string
                      implementation:
                        type: string
                      methods:
                        items:
                          type: string
                        type: array
                      modelUri:
                        type: string
                      name:
                        type: string
                      parameters:
                        items:
                          properties:
                            name:
                              type: string
                            type:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      serviceAccountName:
                        type: string
                      type:
                        type: string
                    type: object
