apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: seldon-model
spec:
  name: test-deployment
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier:1.0
          name: m1
        - image: seldonio/mock_classifier:1.0
          name: m2
        - image: seldonio/mock_classifier:1.0
          name: m3
        - image: seldonio/mock_classifier:1.0
          name: m4
        - image: seldonio/mock_classifier:1.0
          name: m5
    graph:
      name: m1
      type: MODEL
      children:
      - name: m2
        type: MODEL
        children:
        - name: m3
          type: MODEL
          children:
          - name: m4
            type: MODEL
            children:
            - name: m5
              type: MODEL
    name: example
    replicas: 1
