apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/60bed6408732c1eda91a15713f51a9f97dcb1757/tasks/git-clone/git-clone-pr.yaml
  name: integration
spec:
  pipelineSpec:
    tasks:
    - name: integration-test-task
      taskSpec:
        steps:
        - name: pr-build-comment
          image: gcr.io/jenkinsxio/builder-go:2.0.916-264
          dir: ci
          sh: "./add-pr-build-comment"
        - name: integration-step
          env:
            - name: SELDON_E2E_TESTS_TO_RUN
              value: base
            - name: SELDON_E2E_TESTS_POD_INFORMATION
          value: "true"
          command: cd
          args:
            - testing/scripts &&
            - bash
            - kind_test_all.sh
          volumeMounts:
          - mountPath: /lib/modules
            name: modules
            readOnly: true
          - mountPath: /sys/fs/cgroup
            name: cgroup
          - name: dind-storage
            mountPath: /var/lib/docker
          resources:
            requests:
              cpu: 4
              memory: 8000Mi
              ephemeral-storage: "6Gi"
          securityContext:
            privileged: true
          imagePullPolicy: Always
        volumes:
          - name: modules
            hostPath:
              path: /lib/modules
              type: Directory
          - name: cgroup
            hostPath:
              path: /sys/fs/cgroup
              type: Directory
          - name: dind-storage
            emptyDir: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 6h0m0s
status: {}
