apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: integration
spec:
  pipelineSpec:
    tasks:
    - name: integration-test-task
      taskSpec:
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
        - name: pr-build-comment
          image: gcr.io/jenkinsxio/builder-go:2.0.916-264
          dir: ci
          command:
            - sh
          args:
            - ./add-pr-build-comment
        - name: integration-step
          image: seldonio/core-builder:0.19
          env:
            - name: SELDON_E2E_TESTS_TO_RUN
              value: base
            - name: SELDON_E2E_TESTS_POD_INFORMATION
              value: "true"
          command: 
            - cd
          args:
            - testing/scripts &&
            - bash
            - kind_test_all.sh
          volumeMounts:
          - mountPath: /lib/modules
            name: modules
            readOnly: true
          - mountPath: /sys/fs/cgroup
            name: cgroup
          - name: dind-storage
            mountPath: /var/lib/docker
          resources:
            requests:
              cpu: 3
              memory: 8000Mi
              ephemeral-storage: "6Gi"
          securityContext:
            privileged: true
          imagePullPolicy: Always
        volumes:
          - name: modules
            hostPath:
              path: /lib/modules
              type: Directory
          - name: cgroup
            hostPath:
              path: /sys/fs/cgroup
              type: Directory
          - name: dind-storage
            emptyDir: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 6h0m0s
status: {}

