apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      taskSpec:
        steps:
        - name: pr-step
          command:
          - bash
          args:
          - "hello world"
          image: seldonio/core-builder:0.19
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
