apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: print
          image: gcr.io/jenkinsxio/jx-updatebot:latest
          command:
          - echo
          args:
          - "Hello world"
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}

