apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: notebooks
    context: "notebooks"
    always_run: false
    optional: false
    trigger: (?m)^/test( all| notebooks.*),?(s+|$)
    rerun_command: "/test notebooks"
    source: "notebooks.yaml"
  - name: integration
    context: "integration"
    always_run: false
    optional: false
    trigger: (?m)^/test( all| integration.*),?(s+|$)
    rerun_command: "/test integration"
    source: "integration.yaml"
  - name: build-and-push-images
    context: "build-and-push-images"
    always_run: false
    optional: false
    trigger: (?m)^/trigger release(s+|$)
    rerun_command: "/trigger release"
    source: "release.yaml"
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
    - ^main$
    - ^master$

